---
- name: Gather CPU load from all servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Get 1-minute load average
      shell: cat /proc/loadavg | awk '{print $1}'
      register: cpu_load

    - name: Write load result to local file
      delegate_to: localhost
      run_once: false
      lineinfile:
        path: "./files/cpu_loads.txt"
        line: "{{ inventory_hostname }} {{ cpu_load.stdout }}"
        create: yes
